### PR TITLE
Added splay tree data structure and basic tests.

### PR DESCRIPTION
**Pull request by Jakehp**
An extension of a [BST](https://github.com/mgechev/javascript-algorithms/blob/master/src/data-structures/binary-search-tree.js). The tree self adjusts by splaying after an insert, search and remove.

* _splay
* _zigZig
* _zigZag
* _zig
* _splaylessSearch (added since the existing remove method was by node object and not value)

### CODE REVIEW

**Comment by mgechev** [comment]
Thanks for the PR! I'll review it tomorrow.

Could you only fix the jshint errors because the [build breaks](https://travis-ci.org/mgechev/javascript-algorithms/builds/51786266)?

**Comment by Jakehp** [comment]
There we go.

**Comment by mgechev** [comment]
Great! Thanks for the PR!

**Comment by Jakehp** [comment]
np :+1:

**Pull request merged**
