### PR TITLE
Update prime-factor-tree.js

### PR DESCRIPTION
**Pull request by ysharplanguage**
Remarking that: https://primes.utm.edu/notes/faq/six.html

### CODE REVIEW

**Comment by Jakehp** [comment]
```gulp jscs``` fails
https://travis-ci.org/mgechev/javascript-algorithms/jobs/58642330

**Comment by pvoznenko** [comment]
Hi @ysharplanguage I tested your solution against classic prime factor tree and it is really slow. Because factor of complexity in your case is at least n^2 because of loop in loop.

I am not sure, should this solution rewrite classic version of prime factor tree or is it better create separate file with this solution?

Test result:

input value: 600851475143
output: [71, 839, 1471, 6857]

time for calculation classic version: 0.954ms
time for calculation new version: 7.428ms

Here the test: [https://jsfiddle.net/fosco/oL6cf3bh/](https://jsfiddle.net/fosco/oL6cf3bh/)

There are actually existing optimised version of classic algorithm using root of input value. Maybe if I have time I will code it too.

**Comment by ysharplanguage** [comment]
Hi @pvoznenko,

Thanks for your feedback. Your test leaves me a bit perplexical, though.

And what do you get with this:

https://jsfiddle.net/akud5b2d

?

**Comment by pvoznenko** [comment]
@ysharplanguage now I also puzzled :)

I think I figured it out, I using `console.log` and when first time it gets value from the one of our methods it converting it to string and showing to console. When second run is going on (in my test it is `classic`), since it should print the same result, instead of casting array again to the string it takes it out from the cache. 

You can see updated tests: https://jsfiddle.net/fosco/oL6cf3bh/

Thanks, before I did not know that `console.log` cashing results. 

So you right, your solutions is quicker.

**Comment by ysharplanguage** [comment]
Thanks for the update. Interesting, I didn't know either about this console.log peculiarity, or I had forgotten about it.

**Comment by mgechev** [comment]
@ysharplanguage would you fix [the build](https://travis-ci.org/mgechev/javascript-algorithms/builds/58642329) in order to merge it?

**Comment by ysharplanguage** [comment]
@mgechev well, I'd like to, but I have little clue as to what the styling issues were in the first place and how to resolve them.

**Comment by Jakehp** [comment]
https://travis-ci.org/mgechev/javascript-algorithms/builds/58642329

The commands ran to produce the issues and the issues themselves are in the CI build log.

**Comment by mgechev** [comment]
And here are short [guidelines](https://github.com/mgechev/javascript-algorithms#contributions).

**Comment by ysharplanguage** [comment]
Ok, thanks.

**Comment by ysharplanguage** [comment]
(Addressed by pull request #67)

**Pull request closed without merging**
