### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by AndreyGeonya**
List of changes:
1) added package.json
2) changed readme
3) added documentation generator (see readme.md and read how to use it)
4) changed jsdoc and generated documentation for all graph algorithms
5) added debug folder (just for checking that all algorithms works)

How to merge this PR:
1) Merge this code to the master
2) Create gh-pages branch based on master and push it 
As a result you will have documentation like this:
http://andreygeonya.github.io/javascript-algorithms/docs/
by your URL: http://mgechev.github.io/javascript-algorithms/docs/

### CODE REVIEW

**Comment by mgechev** [comment]
This is great idea! I'd love to see the documentation in GitHub pages, online.

This time you've pushed to `master` and I think it is not very appropriate to have generated files there.
Lets keep the JSDocs configuration/build in `master` and everything else in `gh-pages` branch.

What do you think about this idea? Would you initiate a new pull request?

**Comment by AndreyGeonya** [comment]
Hmm, but how we will deliver documentation to github pages?

With generated documentation in `master` we will have the next workflow:
1) accept pull requests (code with jsdoc + generated documentation) to the `master`
2) merge all this stuff to `gh-pages` branch
3) push `master` and `gh-pages` to GitHub

I don't like generated documentation in `master` too, but I don't understand how we will deliver documentation to `origin/gh-pages` according to your proposal... Can you describe it?

**Comment by mgechev** [comment]
Here is how Yeoman's `generator` does this: https://github.com/yeoman/generator/tree/master

They generate their `jsdocs` in directory outside the root of the project and later sync it with the branch `gh-pages`. This way they keep their `master` clean.

**Comment by mgechev** [comment]
I think this process makes sense, although is not completely automated right now.

Lets follow it until we come up to something smarter :confused:

**Pull request closed without merging**
