### PR TITLE
refactor binary-search-tree.js

### PR DESCRIPTION
**Pull request by Xuefeng-Zhu**

### CODE REVIEW

**Comment by mgechev** [comment]
@Xuefeng-Zhu the build is failing. Would you fix it?

**Comment by mgechev** [comment]
The build keeps failing. There are linting errors.

**Comment by Xuefeng-Zhu** [comment]
@mgechev Sorry for the issue, I have fixed the linting errors

**Comment by mgechev** [comment]
Sorry for the delay. It'll be great if you can add tests to make sure the changes don't break anything.

**Pull request closed without merging**
