### PR TITLE
Create size balanced tree for getting the binary tree act like a Javascript Array.

### PR DESCRIPTION
**Pull request by lygstate**
This makes we can using this tree do binary-search /insert/delete after all.
This is closing issue #88

### CODE REVIEW

**Comment by mgechev** [comment]
@lygstate looks great! I'll review the PR tomorrow, merge it and add you to the list of contributors.

Great job!

**Comment by mgechev** [comment]
@lygstate the build is failing because currently we are using ES5 instead of ES2015/2016. Although you are following a good practice, would you change your variable declaration to `var` in order to make the build pass?

**Comment by lygstate** [comment]
Ah, I am using node 4.2.1, that's why it's building OK on my computer.

**Comment by mgechev** [comment]
@lygstate would you change the `let` statements to `var` and commit again? Looks great but I can't merge with the build failing.

**Comment by lygstate** [comment]
@mgechev  The node 0.10 build error is not caused by me, and 0.12 are passed, so I suggest remove node 0.10.

**Comment by mgechev** [comment]
Travis fails again because of invalid value for [nodejs version](https://github.com/mgechev/javascript-algorithms/pull/92/files#diff-354f30a63fb0907d4ad57269548329e3R3). Would you remove `4.x` and try again?

**Pull request merged**
